CREATE TABLE "Master_Department" (
  "Department_id" Auto_increment PRIMARY KEY,
  "Department_name" varchar,
  "Created_at" datetime,
  "Created_by" varchar,
  "Updated_at" datetime,
  "Updated_by" varchar,
  "Deleted_at" datetime
);

CREATE TABLE "Master_Position" (
  "Position_id" Auto_increment PRIMARY KEY,
  "Department_id" integer,
  "Position_name" varchar,
  "Created_at" datetime,
  "Created_by" varchar,
  "Updated_at" datetime,
  "Updated_by" varchar,
  "Deleted_at" datetime
);

CREATE TABLE "Master_Location" (
  "Location_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Location_name" varchar,
  "Created_at" datetime,
  "Created_by" varchar,
  "Updated_at" datetime,
  "Updated_by" varchar,
  "Deleted_at" datetime
);

CREATE TABLE "Employee" (
  "Employee_id" Auto_increment,
  "Employee_code" Varchar,
  "Employee_name" varchar,
  "Password" Varchar(encrypt),
  "Department_id" Integer,
  "Position_id" Integer,
  "Superior" Integer,
  "Created_at" datetime,
  "Created_by" varchar,
  "Updated_at" datetime,
  "Updated_by" varchar,
  "Deleted_at" datetime
);

CREATE TABLE "Attedence" (
  "Attendance_id" Auto_increment,
  "Employee_id" integer,
  "Location_id" integer,
  "Absent_in" datetime,
  "Absent_out" datetime,
  "Created_at" varchar,
  "Created_by" datetime,
  "Updated_at" varchar,
  "Updated_by" datetime,
  "Deleted_at" datetime
);

ALTER TABLE "Master_Position" ADD FOREIGN KEY ("Department_id") REFERENCES "Master_Department" ("Department_id");

ALTER TABLE "Employee" ADD FOREIGN KEY ("Department_id") REFERENCES "Master_Department" ("Department_id");

ALTER TABLE "Employee" ADD FOREIGN KEY ("Position_id") REFERENCES "Master_Position" ("Position_id");

ALTER TABLE "Employee" ADD FOREIGN KEY ("Employee_id") REFERENCES "Attedence" ("Employee_id");

ALTER TABLE "Master_Location" ADD FOREIGN KEY ("Location_id") REFERENCES "Attedence" ("Location_id");
